### ISSUE TITLE
How to move between not adjacent slides

### ISSUE THREAD

**Issue by DavidDom** [aubrijesh/Routerjs#16]
First of all thank you for your awesome work. At this point I can only use the push or pop methods in order to move between slides, but that limits the user to move one slide at a time. Would it be possible to jump to a given slide, like from slide 1 to slide 4, keeping the same animation of the push method? I see a "go" function, witch is used inside the push and pop functions, but haven´t been able to make it work.

Thanks in advanced :)

**Comment by aubrijesh** [comment]
Hi, Thanks for feedback. I have added this feature. You can try it. Now you can pass page index in go function and it will work.

**Comment by aubrijesh** [comment]
feature added.
